baseurl: "https://devcodeabode.github.io/"
title: The Dev Code Abode
author: 
  name: The Dev Code Abode Team
languageCode: en-us
theme: hello-friend-ng
style:
  - css/custom.css
readOtherPosts: Read other posts
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    h1_lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: vim
    tabWidth: 4
permalinks:
  changelog: /changelog/:2006-:01-:02/
params:
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04'
  homeSubtitle: A Home for Code
  disableReadOtherPosts: true
  enableSharingButtons: false
  enableThemeToggle: true
  description: A Home for Code
  keywords: 'discord, bot'
  logo:
    logoText: TDCA
    logoHomeLink: /
  images:
    - ''
  footer:
    trademark: true
    author: true
    copyright: false
    topText:
      - <a target="_blank" href="https://github.com/devcodeabode">GitHub</a>
paginate: 10
taxonomies:
  category: categories
  tag: tags
menu:
  main:
    - identifier: badi
      name: BADI
      url: /badi
    - identifier: spike-3
      name: Spike 3
      url: /spike-3